### ISSUE TITLE
how does this work

### ISSUE THREAD

**Issue by beastbywisdomslave** [OpenGG/swfzip#2]
i understand nothing of whats happening with this thing. can you guys like explain

**Comment by OpenGG** [comment]
This is a compressor/decompressor for SWF files, supporting multiple compression algorithms.

For a SWF file, there is a magic byte indicating how its content is encoded, e.g. `C` for `zlib` compression.

This tool utilize python and multiple libraries to compress/decompress SWF files. For an end user, i.e. normal user without computer science needs or knowledge, this tool is not of great use. For a developer or a SWF-related tool author, however, this tool can be used to manipulate SWF files between different encoding format, making it easier to do reverse engineering.

The installation and usage guide is in in [README.md](https://github.com/OpenGG/swfzip/blob/master/README.md). It should be improve though. Any contribution is welcome.
